// generated by tools/generatePortsInfo.py
#pragma once

#include <string.h>

namespace MVM {
namespace RefPack {
class Ref
{
public:
    Ref() = default;
    virtual ~Ref() = default;
    virtual void exec() = 0;
};



} // namespace RefPack

} // namespace MVM
