//!< generated by tools/generatePortsInfo.py
#pragma once

namespace MVM::RefPack {
class Ref
{
public:
    Ref() = default;
    virtual ~Ref() = default;
    virtual void exec() = 0;
};

} // namespace MVM::RefPack
