// generated by tools/generatePortsInfo.py
#pragma once

#include <string.h>

namespace MVM {
namespace RefPack {
class Memory {
private:
	/* USER JOIN TODO */
    unsigned short mem[4];

public:
    unsigned long clk;
    unsigned long reset;
    unsigned long addr;
    unsigned long wr_en;
    unsigned long rd_en;
    unsigned long wdata;
    unsigned long rdata;

    Memory() {
        memset(mem, 0, sizeof(mem));   
    }
    void eval() {
		/* USER JOIN TODO */
        if (reset) {
            memset(mem, 0, sizeof(mem));
            rdata = 0;
        }
        else {
            if (clk) {
                if (wr_en) {
                    mem[addr] = wdata;
                }
                if (rd_en) {
                    rdata = mem[addr];
                }
            }
        }
	}
};

} // namespace RefPack

} // namespace MVM
