// generated by tools/generatePortsInfo.py
#pragma once

#include <string.h>

namespace MVM {
namespace RefPack {
class Memory {
private:
	/* USER JOIN TODO */
    unsigned short mem[4];

public:
    unsigned long long reset;
    unsigned long long addr;
    unsigned long long wr_en;
    unsigned long long rd_en;
    unsigned long long wdata;
    unsigned long long rdata;

    Memory() {
        memset(mem, 0, sizeof(mem));   
    }
    void eval() {
		/* USER JOIN TODO */
        if (reset) {
            memset(mem, 0, sizeof(mem));
            rdata = 0;
        }
        else {
            if (wr_en) {
                mem[addr] = wdata;
            }
            if (rd_en) {
                rdata = mem[addr];
            }
        }
	}
};

} // namespace RefPack

} // namespace MVM
