// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vnutshellcache.h for the primary calling header

#ifndef VERILATED_VNUTSHELLCACHE_CACHE_H_
#define VERILATED_VNUTSHELLCACHE_CACHE_H_  // guard

#include "verilated.h"
#include "verilated_cov.h"
class Vnutshellcache_Arbiter_4;
class Vnutshellcache_CacheStage1;
class Vnutshellcache_CacheStage2;
class Vnutshellcache_CacheStage3;
class Vnutshellcache_SRAMTemplateWithArbiter;
class Vnutshellcache_SRAMTemplateWithArbiter_1;


class Vnutshellcache__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vnutshellcache_Cache final : public VerilatedModule {
  public:
    // CELLS
    Vnutshellcache_CacheStage1* __PVT__s1;
    Vnutshellcache_CacheStage2* __PVT__s2;
    Vnutshellcache_CacheStage3* __PVT__s3;
    Vnutshellcache_SRAMTemplateWithArbiter* __PVT__metaArray;
    Vnutshellcache_SRAMTemplateWithArbiter_1* __PVT__dataArray;
    Vnutshellcache_Arbiter_4* __PVT__arb;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_in_req_ready,0,0);
        VL_IN8(io_in_req_valid,0,0);
        VL_IN8(io_in_req_bits_size,2,0);
        VL_IN8(io_in_req_bits_cmd,3,0);
        VL_IN8(io_in_req_bits_wmask,7,0);
        VL_IN8(io_in_resp_ready,0,0);
        VL_OUT8(io_in_resp_valid,0,0);
        VL_OUT8(io_in_resp_bits_cmd,3,0);
        VL_IN8(io_flush,1,0);
        VL_IN8(io_out_mem_req_ready,0,0);
        VL_OUT8(io_out_mem_req_valid,0,0);
        VL_OUT8(io_out_mem_req_bits_size,2,0);
        VL_OUT8(io_out_mem_req_bits_cmd,3,0);
        VL_OUT8(io_out_mem_req_bits_wmask,7,0);
        VL_OUT8(io_out_mem_resp_ready,0,0);
        VL_IN8(io_out_mem_resp_valid,0,0);
        VL_IN8(io_out_mem_resp_bits_cmd,3,0);
        VL_OUT8(io_out_coh_req_ready,0,0);
        VL_IN8(io_out_coh_req_valid,0,0);
        VL_IN8(io_out_coh_req_bits_size,2,0);
        VL_IN8(io_out_coh_req_bits_cmd,3,0);
        VL_IN8(io_out_coh_req_bits_wmask,7,0);
        VL_IN8(io_out_coh_resp_ready,0,0);
        VL_OUT8(io_out_coh_resp_valid,0,0);
        VL_OUT8(io_out_coh_resp_bits_cmd,3,0);
        VL_IN8(io_mmio_req_ready,0,0);
        VL_OUT8(io_mmio_req_valid,0,0);
        VL_OUT8(io_mmio_req_bits_size,2,0);
        VL_OUT8(io_mmio_req_bits_cmd,3,0);
        VL_OUT8(io_mmio_req_bits_wmask,7,0);
        VL_OUT8(io_mmio_resp_ready,0,0);
        VL_IN8(io_mmio_resp_valid,0,0);
        VL_IN8(io_mmio_resp_bits_cmd,3,0);
        VL_OUT8(io_empty,0,0);
        VL_OUT8(victimWaymask,3,0);
        CData/*0:0*/ __PVT__s1_io_in_ready;
        CData/*0:0*/ __PVT__s1_io_in_valid;
        CData/*2:0*/ __PVT__s1_io_in_bits_size;
        CData/*3:0*/ __PVT__s1_io_in_bits_cmd;
        CData/*7:0*/ __PVT__s1_io_in_bits_wmask;
        CData/*0:0*/ __PVT__s1_io_out_ready;
        CData/*0:0*/ __PVT__s1_io_out_valid;
        CData/*2:0*/ __PVT__s1_io_out_bits_req_size;
        CData/*3:0*/ __PVT__s1_io_out_bits_req_cmd;
        CData/*7:0*/ __PVT__s1_io_out_bits_req_wmask;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_req_ready;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_req_valid;
        CData/*6:0*/ __PVT__s1_io_metaReadBus_req_bits_setIdx;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_0_valid;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_0_dirty;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_1_valid;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_1_dirty;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_2_valid;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_2_dirty;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_3_valid;
        CData/*0:0*/ __PVT__s1_io_metaReadBus_resp_data_3_dirty;
        CData/*0:0*/ __PVT__s1_io_dataReadBus_req_ready;
        CData/*0:0*/ __PVT__s1_io_dataReadBus_req_valid;
        CData/*0:0*/ __PVT__s2_clock;
        CData/*0:0*/ __PVT__s2_reset;
        CData/*0:0*/ __PVT__s2_io_in_ready;
        CData/*0:0*/ __PVT__s2_io_in_valid;
    };
    struct {
        CData/*2:0*/ __PVT__s2_io_in_bits_req_size;
        CData/*3:0*/ __PVT__s2_io_in_bits_req_cmd;
        CData/*7:0*/ __PVT__s2_io_in_bits_req_wmask;
        CData/*0:0*/ __PVT__s2_io_out_ready;
        CData/*0:0*/ __PVT__s2_io_out_valid;
        CData/*2:0*/ __PVT__s2_io_out_bits_req_size;
        CData/*3:0*/ __PVT__s2_io_out_bits_req_cmd;
        CData/*7:0*/ __PVT__s2_io_out_bits_req_wmask;
        CData/*0:0*/ __PVT__s2_io_out_bits_metas_0_dirty;
        CData/*0:0*/ __PVT__s2_io_out_bits_metas_1_dirty;
        CData/*0:0*/ __PVT__s2_io_out_bits_metas_2_dirty;
        CData/*0:0*/ __PVT__s2_io_out_bits_metas_3_dirty;
        CData/*0:0*/ __PVT__s2_io_out_bits_hit;
        CData/*3:0*/ __PVT__s2_io_out_bits_waymask;
        CData/*0:0*/ __PVT__s2_io_out_bits_mmio;
        CData/*0:0*/ __PVT__s2_io_out_bits_isForwardData;
        CData/*3:0*/ __PVT__s2_io_out_bits_forwardData_waymask;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_0_valid;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_0_dirty;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_1_valid;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_1_dirty;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_2_valid;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_2_dirty;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_3_valid;
        CData/*0:0*/ __PVT__s2_io_metaReadResp_3_dirty;
        CData/*0:0*/ __PVT__s2_io_metaWriteBus_req_valid;
        CData/*6:0*/ __PVT__s2_io_metaWriteBus_req_bits_setIdx;
        CData/*0:0*/ __PVT__s2_io_metaWriteBus_req_bits_data_dirty;
        CData/*3:0*/ __PVT__s2_io_metaWriteBus_req_bits_waymask;
        CData/*0:0*/ __PVT__s2_io_dataWriteBus_req_valid;
        CData/*3:0*/ __PVT__s2_io_dataWriteBus_req_bits_waymask;
        CData/*0:0*/ __PVT__s3_clock;
        CData/*0:0*/ __PVT__s3_reset;
        CData/*0:0*/ __PVT__s3_io_in_ready;
        CData/*0:0*/ __PVT__s3_io_in_valid;
        CData/*2:0*/ __PVT__s3_io_in_bits_req_size;
        CData/*3:0*/ __PVT__s3_io_in_bits_req_cmd;
        CData/*7:0*/ __PVT__s3_io_in_bits_req_wmask;
        CData/*0:0*/ __PVT__s3_io_in_bits_metas_0_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_metas_1_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_metas_2_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_metas_3_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_hit;
        CData/*3:0*/ __PVT__s3_io_in_bits_waymask;
        CData/*0:0*/ __PVT__s3_io_in_bits_mmio;
        CData/*0:0*/ __PVT__s3_io_in_bits_isForwardData;
        CData/*3:0*/ __PVT__s3_io_in_bits_forwardData_waymask;
        CData/*0:0*/ __PVT__s3_io_out_ready;
        CData/*0:0*/ __PVT__s3_io_out_valid;
        CData/*3:0*/ __PVT__s3_io_out_bits_cmd;
        CData/*0:0*/ __PVT__s3_io_isFinish;
        CData/*0:0*/ __PVT__s3_io_flush;
        CData/*0:0*/ __PVT__s3_io_dataReadBus_req_ready;
        CData/*0:0*/ __PVT__s3_io_dataReadBus_req_valid;
        CData/*0:0*/ __PVT__s3_io_dataWriteBus_req_valid;
        CData/*3:0*/ __PVT__s3_io_dataWriteBus_req_bits_waymask;
        CData/*0:0*/ __PVT__s3_io_metaWriteBus_req_valid;
        CData/*6:0*/ __PVT__s3_io_metaWriteBus_req_bits_setIdx;
        CData/*0:0*/ __PVT__s3_io_metaWriteBus_req_bits_data_dirty;
        CData/*3:0*/ __PVT__s3_io_metaWriteBus_req_bits_waymask;
        CData/*0:0*/ __PVT__s3_io_mem_req_ready;
        CData/*0:0*/ __PVT__s3_io_mem_req_valid;
        CData/*3:0*/ __PVT__s3_io_mem_req_bits_cmd;
        CData/*0:0*/ __PVT__s3_io_mem_resp_ready;
    };
    struct {
        CData/*0:0*/ __PVT__s3_io_mem_resp_valid;
        CData/*3:0*/ __PVT__s3_io_mem_resp_bits_cmd;
        CData/*0:0*/ __PVT__s3_io_mmio_req_ready;
        CData/*0:0*/ __PVT__s3_io_mmio_req_valid;
        CData/*2:0*/ __PVT__s3_io_mmio_req_bits_size;
        CData/*3:0*/ __PVT__s3_io_mmio_req_bits_cmd;
        CData/*7:0*/ __PVT__s3_io_mmio_req_bits_wmask;
        CData/*0:0*/ __PVT__s3_io_mmio_resp_ready;
        CData/*0:0*/ __PVT__s3_io_mmio_resp_valid;
        CData/*0:0*/ __PVT__s3_io_cohResp_ready;
        CData/*0:0*/ __PVT__s3_io_cohResp_valid;
        CData/*3:0*/ __PVT__s3_io_cohResp_bits_cmd;
        CData/*0:0*/ __PVT__s3_io_dataReadRespToL1;
        CData/*0:0*/ __PVT__metaArray_clock;
        CData/*0:0*/ __PVT__metaArray_reset;
        CData/*0:0*/ __PVT__metaArray_io_r_0_req_ready;
        CData/*0:0*/ __PVT__metaArray_io_r_0_req_valid;
        CData/*6:0*/ __PVT__metaArray_io_r_0_req_bits_setIdx;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_0_valid;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_0_dirty;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_1_valid;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_1_dirty;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_2_valid;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_2_dirty;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_3_valid;
        CData/*0:0*/ __PVT__metaArray_io_r_0_resp_data_3_dirty;
        CData/*0:0*/ __PVT__metaArray_io_w_req_valid;
        CData/*6:0*/ __PVT__metaArray_io_w_req_bits_setIdx;
        CData/*0:0*/ __PVT__metaArray_io_w_req_bits_data_dirty;
        CData/*3:0*/ __PVT__metaArray_io_w_req_bits_waymask;
        CData/*0:0*/ __PVT__dataArray_clock;
        CData/*0:0*/ __PVT__dataArray_reset;
        CData/*0:0*/ __PVT__dataArray_io_r_0_req_ready;
        CData/*0:0*/ __PVT__dataArray_io_r_0_req_valid;
        CData/*0:0*/ __PVT__dataArray_io_r_1_req_ready;
        CData/*0:0*/ __PVT__dataArray_io_r_1_req_valid;
        CData/*0:0*/ __PVT__dataArray_io_w_req_valid;
        CData/*3:0*/ __PVT__dataArray_io_w_req_bits_waymask;
        CData/*0:0*/ __PVT__arb_io_in_0_ready;
        CData/*0:0*/ __PVT__arb_io_in_0_valid;
        CData/*2:0*/ __PVT__arb_io_in_0_bits_size;
        CData/*3:0*/ __PVT__arb_io_in_0_bits_cmd;
        CData/*7:0*/ __PVT__arb_io_in_0_bits_wmask;
        CData/*0:0*/ __PVT__arb_io_in_1_ready;
        CData/*0:0*/ __PVT__arb_io_in_1_valid;
        CData/*2:0*/ __PVT__arb_io_in_1_bits_size;
        CData/*3:0*/ __PVT__arb_io_in_1_bits_cmd;
        CData/*7:0*/ __PVT__arb_io_in_1_bits_wmask;
        CData/*0:0*/ __PVT__arb_io_out_ready;
        CData/*0:0*/ __PVT__arb_io_out_valid;
        CData/*2:0*/ __PVT__arb_io_out_bits_size;
        CData/*3:0*/ __PVT__arb_io_out_bits_cmd;
        CData/*7:0*/ __PVT__arb_io_out_bits_wmask;
        CData/*0:0*/ __PVT___T;
        CData/*0:0*/ __PVT__valid;
        CData/*0:0*/ __PVT___GEN_0;
        CData/*0:0*/ __PVT___T_2;
        CData/*0:0*/ __PVT___GEN_1;
        CData/*2:0*/ __PVT__s2_io_in_bits_r_req_size;
        CData/*3:0*/ __PVT__s2_io_in_bits_r_req_cmd;
        CData/*7:0*/ __PVT__s2_io_in_bits_r_req_wmask;
        CData/*0:0*/ __PVT__valid_1;
        CData/*0:0*/ __PVT___GEN_9;
        CData/*0:0*/ __PVT___T_4;
    };
    struct {
        CData/*0:0*/ __PVT___GEN_10;
        CData/*2:0*/ __PVT__s3_io_in_bits_r_req_size;
        CData/*3:0*/ __PVT__s3_io_in_bits_r_req_cmd;
        CData/*7:0*/ __PVT__s3_io_in_bits_r_req_wmask;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_metas_0_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_metas_1_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_metas_2_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_metas_3_dirty;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_hit;
        CData/*3:0*/ __PVT__s3_io_in_bits_r_waymask;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_mmio;
        CData/*0:0*/ __PVT__s3_io_in_bits_r_isForwardData;
        CData/*3:0*/ __PVT__s3_io_in_bits_r_forwardData_waymask;
        CData/*0:0*/ __PVT___io_in_resp_valid_T;
        CData/*0:0*/ __Vtogcov__clock;
        CData/*0:0*/ __Vtogcov__reset;
        CData/*0:0*/ __Vtogcov__io_in_req_ready;
        CData/*0:0*/ __Vtogcov__io_in_req_valid;
        CData/*2:0*/ __Vtogcov__io_in_req_bits_size;
        CData/*3:0*/ __Vtogcov__io_in_req_bits_cmd;
        CData/*7:0*/ __Vtogcov__io_in_req_bits_wmask;
        CData/*0:0*/ __Vtogcov__io_in_resp_ready;
        CData/*0:0*/ __Vtogcov__io_in_resp_valid;
        CData/*3:0*/ __Vtogcov__io_in_resp_bits_cmd;
        CData/*1:0*/ __Vtogcov__io_flush;
        CData/*0:0*/ __Vtogcov__io_out_mem_req_ready;
        CData/*0:0*/ __Vtogcov__io_out_mem_req_valid;
        CData/*2:0*/ __Vtogcov__io_out_mem_req_bits_size;
        CData/*3:0*/ __Vtogcov__io_out_mem_req_bits_cmd;
        CData/*7:0*/ __Vtogcov__io_out_mem_req_bits_wmask;
        CData/*0:0*/ __Vtogcov__io_out_mem_resp_ready;
        CData/*0:0*/ __Vtogcov__io_out_mem_resp_valid;
        CData/*3:0*/ __Vtogcov__io_out_mem_resp_bits_cmd;
        CData/*0:0*/ __Vtogcov__io_out_coh_req_ready;
        CData/*0:0*/ __Vtogcov__io_out_coh_req_valid;
        CData/*2:0*/ __Vtogcov__io_out_coh_req_bits_size;
        CData/*3:0*/ __Vtogcov__io_out_coh_req_bits_cmd;
        CData/*7:0*/ __Vtogcov__io_out_coh_req_bits_wmask;
        CData/*0:0*/ __Vtogcov__io_out_coh_resp_ready;
        CData/*0:0*/ __Vtogcov__io_out_coh_resp_valid;
        CData/*3:0*/ __Vtogcov__io_out_coh_resp_bits_cmd;
        CData/*0:0*/ __Vtogcov__io_mmio_req_ready;
        CData/*0:0*/ __Vtogcov__io_mmio_req_valid;
        CData/*2:0*/ __Vtogcov__io_mmio_req_bits_size;
        CData/*3:0*/ __Vtogcov__io_mmio_req_bits_cmd;
        CData/*7:0*/ __Vtogcov__io_mmio_req_bits_wmask;
        CData/*0:0*/ __Vtogcov__io_mmio_resp_ready;
        CData/*0:0*/ __Vtogcov__io_mmio_resp_valid;
        CData/*3:0*/ __Vtogcov__io_mmio_resp_bits_cmd;
        CData/*0:0*/ __Vtogcov__io_empty;
        CData/*3:0*/ __Vtogcov__victimWaymask;
        CData/*0:0*/ __Vtogcov__s1_io_in_ready;
        CData/*0:0*/ __Vtogcov__s1_io_in_valid;
        CData/*2:0*/ __Vtogcov__s1_io_in_bits_size;
        CData/*3:0*/ __Vtogcov__s1_io_in_bits_cmd;
        CData/*7:0*/ __Vtogcov__s1_io_in_bits_wmask;
        CData/*0:0*/ __Vtogcov__s1_io_out_ready;
        CData/*0:0*/ __Vtogcov__s1_io_out_valid;
        CData/*2:0*/ __Vtogcov__s1_io_out_bits_req_size;
        CData/*3:0*/ __Vtogcov__s1_io_out_bits_req_cmd;
        CData/*7:0*/ __Vtogcov__s1_io_out_bits_req_wmask;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_req_ready;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_req_valid;
        CData/*6:0*/ __Vtogcov__s1_io_metaReadBus_req_bits_setIdx;
    };
    struct {
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_0_valid;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_0_dirty;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_1_valid;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_1_dirty;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_2_valid;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_2_dirty;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_3_valid;
        CData/*0:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_3_dirty;
        CData/*0:0*/ __Vtogcov__s1_io_dataReadBus_req_ready;
        CData/*0:0*/ __Vtogcov__s1_io_dataReadBus_req_valid;
        CData/*0:0*/ __Vtogcov__s2_clock;
        CData/*0:0*/ __Vtogcov__s2_reset;
        CData/*0:0*/ __Vtogcov__s2_io_in_ready;
        CData/*0:0*/ __Vtogcov__s2_io_in_valid;
        CData/*2:0*/ __Vtogcov__s2_io_in_bits_req_size;
        CData/*3:0*/ __Vtogcov__s2_io_in_bits_req_cmd;
        CData/*7:0*/ __Vtogcov__s2_io_in_bits_req_wmask;
        CData/*0:0*/ __Vtogcov__s2_io_out_ready;
        CData/*0:0*/ __Vtogcov__s2_io_out_valid;
        CData/*2:0*/ __Vtogcov__s2_io_out_bits_req_size;
        CData/*3:0*/ __Vtogcov__s2_io_out_bits_req_cmd;
        CData/*7:0*/ __Vtogcov__s2_io_out_bits_req_wmask;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_metas_0_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_metas_1_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_metas_2_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_metas_3_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_hit;
        CData/*3:0*/ __Vtogcov__s2_io_out_bits_waymask;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_mmio;
        CData/*0:0*/ __Vtogcov__s2_io_out_bits_isForwardData;
        CData/*3:0*/ __Vtogcov__s2_io_out_bits_forwardData_waymask;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_0_valid;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_0_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_1_valid;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_1_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_2_valid;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_2_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_3_valid;
        CData/*0:0*/ __Vtogcov__s2_io_metaReadResp_3_dirty;
        CData/*0:0*/ __Vtogcov__s2_io_metaWriteBus_req_valid;
        CData/*6:0*/ __Vtogcov__s2_io_metaWriteBus_req_bits_setIdx;
        CData/*0:0*/ __Vtogcov__s2_io_metaWriteBus_req_bits_data_dirty;
        CData/*3:0*/ __Vtogcov__s2_io_metaWriteBus_req_bits_waymask;
        CData/*0:0*/ __Vtogcov__s2_io_dataWriteBus_req_valid;
        CData/*3:0*/ __Vtogcov__s2_io_dataWriteBus_req_bits_waymask;
        CData/*0:0*/ __Vtogcov__s3_clock;
        CData/*0:0*/ __Vtogcov__s3_reset;
        CData/*0:0*/ __Vtogcov__s3_io_in_ready;
        CData/*0:0*/ __Vtogcov__s3_io_in_valid;
        CData/*2:0*/ __Vtogcov__s3_io_in_bits_req_size;
        CData/*3:0*/ __Vtogcov__s3_io_in_bits_req_cmd;
        CData/*7:0*/ __Vtogcov__s3_io_in_bits_req_wmask;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_metas_0_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_metas_1_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_metas_2_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_metas_3_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_hit;
        CData/*3:0*/ __Vtogcov__s3_io_in_bits_waymask;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_mmio;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_isForwardData;
        CData/*3:0*/ __Vtogcov__s3_io_in_bits_forwardData_waymask;
        CData/*0:0*/ __Vtogcov__s3_io_out_ready;
        CData/*0:0*/ __Vtogcov__s3_io_out_valid;
        CData/*3:0*/ __Vtogcov__s3_io_out_bits_cmd;
    };
    struct {
        CData/*0:0*/ __Vtogcov__s3_io_isFinish;
        CData/*0:0*/ __Vtogcov__s3_io_flush;
        CData/*0:0*/ __Vtogcov__s3_io_dataReadBus_req_ready;
        CData/*0:0*/ __Vtogcov__s3_io_dataReadBus_req_valid;
        CData/*0:0*/ __Vtogcov__s3_io_dataWriteBus_req_valid;
        CData/*3:0*/ __Vtogcov__s3_io_dataWriteBus_req_bits_waymask;
        CData/*0:0*/ __Vtogcov__s3_io_metaWriteBus_req_valid;
        CData/*6:0*/ __Vtogcov__s3_io_metaWriteBus_req_bits_setIdx;
        CData/*0:0*/ __Vtogcov__s3_io_metaWriteBus_req_bits_data_dirty;
        CData/*3:0*/ __Vtogcov__s3_io_metaWriteBus_req_bits_waymask;
        CData/*0:0*/ __Vtogcov__s3_io_mem_req_ready;
        CData/*0:0*/ __Vtogcov__s3_io_mem_req_valid;
        CData/*3:0*/ __Vtogcov__s3_io_mem_req_bits_cmd;
        CData/*0:0*/ __Vtogcov__s3_io_mem_resp_ready;
        CData/*0:0*/ __Vtogcov__s3_io_mem_resp_valid;
        CData/*3:0*/ __Vtogcov__s3_io_mem_resp_bits_cmd;
        CData/*0:0*/ __Vtogcov__s3_io_mmio_req_ready;
        CData/*0:0*/ __Vtogcov__s3_io_mmio_req_valid;
        CData/*2:0*/ __Vtogcov__s3_io_mmio_req_bits_size;
        CData/*3:0*/ __Vtogcov__s3_io_mmio_req_bits_cmd;
        CData/*7:0*/ __Vtogcov__s3_io_mmio_req_bits_wmask;
        CData/*0:0*/ __Vtogcov__s3_io_mmio_resp_ready;
        CData/*0:0*/ __Vtogcov__s3_io_mmio_resp_valid;
        CData/*0:0*/ __Vtogcov__s3_io_cohResp_ready;
        CData/*0:0*/ __Vtogcov__s3_io_cohResp_valid;
        CData/*3:0*/ __Vtogcov__s3_io_cohResp_bits_cmd;
        CData/*0:0*/ __Vtogcov__s3_io_dataReadRespToL1;
        CData/*0:0*/ __Vtogcov__metaArray_clock;
        CData/*0:0*/ __Vtogcov__metaArray_reset;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_req_ready;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_req_valid;
        CData/*6:0*/ __Vtogcov__metaArray_io_r_0_req_bits_setIdx;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_0_valid;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_0_dirty;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_1_valid;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_1_dirty;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_2_valid;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_2_dirty;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_3_valid;
        CData/*0:0*/ __Vtogcov__metaArray_io_r_0_resp_data_3_dirty;
        CData/*0:0*/ __Vtogcov__metaArray_io_w_req_valid;
        CData/*6:0*/ __Vtogcov__metaArray_io_w_req_bits_setIdx;
        CData/*0:0*/ __Vtogcov__metaArray_io_w_req_bits_data_dirty;
        CData/*3:0*/ __Vtogcov__metaArray_io_w_req_bits_waymask;
        CData/*0:0*/ __Vtogcov__dataArray_clock;
        CData/*0:0*/ __Vtogcov__dataArray_reset;
        CData/*0:0*/ __Vtogcov__dataArray_io_r_0_req_ready;
        CData/*0:0*/ __Vtogcov__dataArray_io_r_0_req_valid;
        CData/*0:0*/ __Vtogcov__dataArray_io_r_1_req_ready;
        CData/*0:0*/ __Vtogcov__dataArray_io_r_1_req_valid;
        CData/*0:0*/ __Vtogcov__dataArray_io_w_req_valid;
        CData/*3:0*/ __Vtogcov__dataArray_io_w_req_bits_waymask;
        CData/*0:0*/ __Vtogcov__arb_io_in_0_ready;
        CData/*0:0*/ __Vtogcov__arb_io_in_0_valid;
        CData/*2:0*/ __Vtogcov__arb_io_in_0_bits_size;
        CData/*3:0*/ __Vtogcov__arb_io_in_0_bits_cmd;
        CData/*7:0*/ __Vtogcov__arb_io_in_0_bits_wmask;
        CData/*0:0*/ __Vtogcov__arb_io_in_1_ready;
        CData/*0:0*/ __Vtogcov__arb_io_in_1_valid;
        CData/*2:0*/ __Vtogcov__arb_io_in_1_bits_size;
        CData/*3:0*/ __Vtogcov__arb_io_in_1_bits_cmd;
        CData/*7:0*/ __Vtogcov__arb_io_in_1_bits_wmask;
        CData/*0:0*/ __Vtogcov__arb_io_out_ready;
        CData/*0:0*/ __Vtogcov__arb_io_out_valid;
    };
    struct {
        CData/*2:0*/ __Vtogcov__arb_io_out_bits_size;
        CData/*3:0*/ __Vtogcov__arb_io_out_bits_cmd;
        CData/*7:0*/ __Vtogcov__arb_io_out_bits_wmask;
        CData/*0:0*/ __Vtogcov__valid;
        CData/*2:0*/ __Vtogcov__s2_io_in_bits_r_req_size;
        CData/*3:0*/ __Vtogcov__s2_io_in_bits_r_req_cmd;
        CData/*7:0*/ __Vtogcov__s2_io_in_bits_r_req_wmask;
        CData/*0:0*/ __Vtogcov__valid_1;
        CData/*2:0*/ __Vtogcov__s3_io_in_bits_r_req_size;
        CData/*3:0*/ __Vtogcov__s3_io_in_bits_r_req_cmd;
        CData/*7:0*/ __Vtogcov__s3_io_in_bits_r_req_wmask;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_metas_0_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_metas_1_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_metas_2_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_metas_3_dirty;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_hit;
        CData/*3:0*/ __Vtogcov__s3_io_in_bits_r_waymask;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_mmio;
        CData/*0:0*/ __Vtogcov__s3_io_in_bits_r_isForwardData;
        CData/*3:0*/ __Vtogcov__s3_io_in_bits_r_forwardData_waymask;
        CData/*0:0*/ __Vdly__valid;
        CData/*2:0*/ __Vdly__s2_io_in_bits_r_req_size;
        CData/*3:0*/ __Vdly__s2_io_in_bits_r_req_cmd;
        CData/*7:0*/ __Vdly__s2_io_in_bits_r_req_wmask;
        CData/*0:0*/ __Vdly__valid_1;
        CData/*2:0*/ __Vdly__s3_io_in_bits_r_req_size;
        CData/*3:0*/ __Vdly__s3_io_in_bits_r_req_cmd;
        CData/*7:0*/ __Vdly__s3_io_in_bits_r_req_wmask;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_metas_0_dirty;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_metas_1_dirty;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_metas_2_dirty;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_metas_3_dirty;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_hit;
        CData/*3:0*/ __Vdly__s3_io_in_bits_r_waymask;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_mmio;
        CData/*0:0*/ __Vdly__s3_io_in_bits_r_isForwardData;
        CData/*3:0*/ __Vdly__s3_io_in_bits_r_forwardData_waymask;
        VL_IN16(io_in_req_bits_user,15,0);
        VL_OUT16(io_in_resp_bits_user,15,0);
        SData/*15:0*/ __PVT__s1_io_in_bits_user;
        SData/*15:0*/ __PVT__s1_io_out_bits_req_user;
        SData/*9:0*/ __PVT__s1_io_dataReadBus_req_bits_setIdx;
        SData/*15:0*/ __PVT__s2_io_in_bits_req_user;
        SData/*15:0*/ __PVT__s2_io_out_bits_req_user;
        SData/*9:0*/ __PVT__s2_io_dataWriteBus_req_bits_setIdx;
        SData/*15:0*/ __PVT__s3_io_in_bits_req_user;
        SData/*15:0*/ __PVT__s3_io_out_bits_user;
        SData/*9:0*/ __PVT__s3_io_dataReadBus_req_bits_setIdx;
        SData/*9:0*/ __PVT__s3_io_dataWriteBus_req_bits_setIdx;
        SData/*9:0*/ __PVT__dataArray_io_r_0_req_bits_setIdx;
        SData/*9:0*/ __PVT__dataArray_io_r_1_req_bits_setIdx;
        SData/*9:0*/ __PVT__dataArray_io_w_req_bits_setIdx;
        SData/*15:0*/ __PVT__arb_io_in_1_bits_user;
        SData/*15:0*/ __PVT__arb_io_out_bits_user;
        SData/*15:0*/ __PVT__s2_io_in_bits_r_req_user;
        SData/*15:0*/ __PVT__s3_io_in_bits_r_req_user;
        SData/*15:0*/ __Vtogcov__io_in_req_bits_user;
        SData/*15:0*/ __Vtogcov__io_in_resp_bits_user;
        SData/*15:0*/ __Vtogcov__s1_io_in_bits_user;
        SData/*15:0*/ __Vtogcov__s1_io_out_bits_req_user;
        SData/*9:0*/ __Vtogcov__s1_io_dataReadBus_req_bits_setIdx;
        SData/*15:0*/ __Vtogcov__s2_io_in_bits_req_user;
        SData/*15:0*/ __Vtogcov__s2_io_out_bits_req_user;
        SData/*9:0*/ __Vtogcov__s2_io_dataWriteBus_req_bits_setIdx;
    };
    struct {
        SData/*15:0*/ __Vtogcov__s3_io_in_bits_req_user;
        SData/*15:0*/ __Vtogcov__s3_io_out_bits_user;
        SData/*9:0*/ __Vtogcov__s3_io_dataReadBus_req_bits_setIdx;
        SData/*9:0*/ __Vtogcov__s3_io_dataWriteBus_req_bits_setIdx;
        SData/*9:0*/ __Vtogcov__dataArray_io_r_0_req_bits_setIdx;
        SData/*9:0*/ __Vtogcov__dataArray_io_r_1_req_bits_setIdx;
        SData/*9:0*/ __Vtogcov__dataArray_io_w_req_bits_setIdx;
        SData/*15:0*/ __Vtogcov__arb_io_in_1_bits_user;
        SData/*15:0*/ __Vtogcov__arb_io_out_bits_user;
        SData/*15:0*/ __Vtogcov__s2_io_in_bits_r_req_user;
        SData/*15:0*/ __Vtogcov__s3_io_in_bits_r_req_user;
        SData/*15:0*/ __Vdly__s2_io_in_bits_r_req_user;
        SData/*15:0*/ __Vdly__s3_io_in_bits_r_req_user;
        VL_IN(io_in_req_bits_addr,31,0);
        VL_OUT(io_out_mem_req_bits_addr,31,0);
        VL_IN(io_out_coh_req_bits_addr,31,0);
        VL_OUT(io_mmio_req_bits_addr,31,0);
        IData/*31:0*/ __PVT__s1_io_in_bits_addr;
        IData/*31:0*/ __PVT__s1_io_out_bits_req_addr;
        IData/*18:0*/ __PVT__s1_io_metaReadBus_resp_data_0_tag;
        IData/*18:0*/ __PVT__s1_io_metaReadBus_resp_data_1_tag;
        IData/*18:0*/ __PVT__s1_io_metaReadBus_resp_data_2_tag;
        IData/*18:0*/ __PVT__s1_io_metaReadBus_resp_data_3_tag;
        IData/*31:0*/ __PVT__s2_io_in_bits_req_addr;
        IData/*31:0*/ __PVT__s2_io_out_bits_req_addr;
        IData/*18:0*/ __PVT__s2_io_out_bits_metas_0_tag;
        IData/*18:0*/ __PVT__s2_io_out_bits_metas_1_tag;
        IData/*18:0*/ __PVT__s2_io_out_bits_metas_2_tag;
        IData/*18:0*/ __PVT__s2_io_out_bits_metas_3_tag;
        IData/*18:0*/ __PVT__s2_io_metaReadResp_0_tag;
        IData/*18:0*/ __PVT__s2_io_metaReadResp_1_tag;
        IData/*18:0*/ __PVT__s2_io_metaReadResp_2_tag;
        IData/*18:0*/ __PVT__s2_io_metaReadResp_3_tag;
        IData/*18:0*/ __PVT__s2_io_metaWriteBus_req_bits_data_tag;
        IData/*31:0*/ __PVT__s3_io_in_bits_req_addr;
        IData/*18:0*/ __PVT__s3_io_in_bits_metas_0_tag;
        IData/*18:0*/ __PVT__s3_io_in_bits_metas_1_tag;
        IData/*18:0*/ __PVT__s3_io_in_bits_metas_2_tag;
        IData/*18:0*/ __PVT__s3_io_in_bits_metas_3_tag;
        IData/*18:0*/ __PVT__s3_io_metaWriteBus_req_bits_data_tag;
        IData/*31:0*/ __PVT__s3_io_mem_req_bits_addr;
        IData/*31:0*/ __PVT__s3_io_mmio_req_bits_addr;
        IData/*18:0*/ __PVT__metaArray_io_r_0_resp_data_0_tag;
        IData/*18:0*/ __PVT__metaArray_io_r_0_resp_data_1_tag;
        IData/*18:0*/ __PVT__metaArray_io_r_0_resp_data_2_tag;
        IData/*18:0*/ __PVT__metaArray_io_r_0_resp_data_3_tag;
        IData/*18:0*/ __PVT__metaArray_io_w_req_bits_data_tag;
        IData/*31:0*/ __PVT__arb_io_in_0_bits_addr;
        IData/*31:0*/ __PVT__arb_io_in_1_bits_addr;
        IData/*31:0*/ __PVT__arb_io_out_bits_addr;
        IData/*31:0*/ __PVT__s2_io_in_bits_r_req_addr;
        IData/*31:0*/ __PVT__s3_io_in_bits_r_req_addr;
        IData/*18:0*/ __PVT__s3_io_in_bits_r_metas_0_tag;
        IData/*18:0*/ __PVT__s3_io_in_bits_r_metas_1_tag;
        IData/*18:0*/ __PVT__s3_io_in_bits_r_metas_2_tag;
        IData/*18:0*/ __PVT__s3_io_in_bits_r_metas_3_tag;
        IData/*31:0*/ __Vtogcov__io_in_req_bits_addr;
        IData/*31:0*/ __Vtogcov__io_out_mem_req_bits_addr;
        IData/*31:0*/ __Vtogcov__io_out_coh_req_bits_addr;
        IData/*31:0*/ __Vtogcov__io_mmio_req_bits_addr;
        IData/*31:0*/ __Vtogcov__s1_io_in_bits_addr;
        IData/*31:0*/ __Vtogcov__s1_io_out_bits_req_addr;
        IData/*18:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_0_tag;
        IData/*18:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_1_tag;
    };
    struct {
        IData/*18:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_2_tag;
        IData/*18:0*/ __Vtogcov__s1_io_metaReadBus_resp_data_3_tag;
        IData/*31:0*/ __Vtogcov__s2_io_in_bits_req_addr;
        IData/*31:0*/ __Vtogcov__s2_io_out_bits_req_addr;
        IData/*18:0*/ __Vtogcov__s2_io_out_bits_metas_0_tag;
        IData/*18:0*/ __Vtogcov__s2_io_out_bits_metas_1_tag;
        IData/*18:0*/ __Vtogcov__s2_io_out_bits_metas_2_tag;
        IData/*18:0*/ __Vtogcov__s2_io_out_bits_metas_3_tag;
        IData/*18:0*/ __Vtogcov__s2_io_metaReadResp_0_tag;
        IData/*18:0*/ __Vtogcov__s2_io_metaReadResp_1_tag;
        IData/*18:0*/ __Vtogcov__s2_io_metaReadResp_2_tag;
        IData/*18:0*/ __Vtogcov__s2_io_metaReadResp_3_tag;
        IData/*18:0*/ __Vtogcov__s2_io_metaWriteBus_req_bits_data_tag;
        IData/*31:0*/ __Vtogcov__s3_io_in_bits_req_addr;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_metas_0_tag;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_metas_1_tag;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_metas_2_tag;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_metas_3_tag;
        IData/*18:0*/ __Vtogcov__s3_io_metaWriteBus_req_bits_data_tag;
        IData/*31:0*/ __Vtogcov__s3_io_mem_req_bits_addr;
        IData/*31:0*/ __Vtogcov__s3_io_mmio_req_bits_addr;
        IData/*18:0*/ __Vtogcov__metaArray_io_r_0_resp_data_0_tag;
        IData/*18:0*/ __Vtogcov__metaArray_io_r_0_resp_data_1_tag;
        IData/*18:0*/ __Vtogcov__metaArray_io_r_0_resp_data_2_tag;
        IData/*18:0*/ __Vtogcov__metaArray_io_r_0_resp_data_3_tag;
        IData/*18:0*/ __Vtogcov__metaArray_io_w_req_bits_data_tag;
        IData/*31:0*/ __Vtogcov__arb_io_in_0_bits_addr;
        IData/*31:0*/ __Vtogcov__arb_io_in_1_bits_addr;
        IData/*31:0*/ __Vtogcov__arb_io_out_bits_addr;
        IData/*31:0*/ __Vtogcov__s2_io_in_bits_r_req_addr;
        IData/*31:0*/ __Vtogcov__s3_io_in_bits_r_req_addr;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_r_metas_0_tag;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_r_metas_1_tag;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_r_metas_2_tag;
        IData/*18:0*/ __Vtogcov__s3_io_in_bits_r_metas_3_tag;
        IData/*31:0*/ __Vdly__s2_io_in_bits_r_req_addr;
        IData/*31:0*/ __Vdly__s3_io_in_bits_r_req_addr;
        IData/*18:0*/ __Vdly__s3_io_in_bits_r_metas_0_tag;
        IData/*18:0*/ __Vdly__s3_io_in_bits_r_metas_1_tag;
        IData/*18:0*/ __Vdly__s3_io_in_bits_r_metas_2_tag;
        IData/*18:0*/ __Vdly__s3_io_in_bits_r_metas_3_tag;
        VL_IN64(io_in_req_bits_wdata,63,0);
        VL_OUT64(io_in_resp_bits_rdata,63,0);
        VL_OUT64(io_out_mem_req_bits_wdata,63,0);
        VL_IN64(io_out_mem_resp_bits_rdata,63,0);
        VL_IN64(io_out_coh_req_bits_wdata,63,0);
        VL_OUT64(io_out_coh_resp_bits_rdata,63,0);
        VL_OUT64(io_mmio_req_bits_wdata,63,0);
        VL_IN64(io_mmio_resp_bits_rdata,63,0);
        QData/*63:0*/ __PVT__s1_io_in_bits_wdata;
        QData/*63:0*/ __PVT__s1_io_out_bits_req_wdata;
        QData/*63:0*/ __PVT__s1_io_dataReadBus_resp_data_0_data;
        QData/*63:0*/ __PVT__s1_io_dataReadBus_resp_data_1_data;
        QData/*63:0*/ __PVT__s1_io_dataReadBus_resp_data_2_data;
        QData/*63:0*/ __PVT__s1_io_dataReadBus_resp_data_3_data;
        QData/*63:0*/ __PVT__s2_io_in_bits_req_wdata;
        QData/*63:0*/ __PVT__s2_io_out_bits_req_wdata;
        QData/*63:0*/ __PVT__s2_io_out_bits_datas_0_data;
        QData/*63:0*/ __PVT__s2_io_out_bits_datas_1_data;
        QData/*63:0*/ __PVT__s2_io_out_bits_datas_2_data;
        QData/*63:0*/ __PVT__s2_io_out_bits_datas_3_data;
        QData/*63:0*/ __PVT__s2_io_out_bits_forwardData_data_data;
        QData/*63:0*/ __PVT__s2_io_dataReadResp_0_data;
        QData/*63:0*/ __PVT__s2_io_dataReadResp_1_data;
    };
    struct {
        QData/*63:0*/ __PVT__s2_io_dataReadResp_2_data;
        QData/*63:0*/ __PVT__s2_io_dataReadResp_3_data;
        QData/*63:0*/ __PVT__s2_io_dataWriteBus_req_bits_data_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_req_wdata;
        QData/*63:0*/ __PVT__s3_io_in_bits_datas_0_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_datas_1_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_datas_2_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_datas_3_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_forwardData_data_data;
        QData/*63:0*/ __PVT__s3_io_out_bits_rdata;
        QData/*63:0*/ __PVT__s3_io_dataReadBus_resp_data_0_data;
        QData/*63:0*/ __PVT__s3_io_dataReadBus_resp_data_1_data;
        QData/*63:0*/ __PVT__s3_io_dataReadBus_resp_data_2_data;
        QData/*63:0*/ __PVT__s3_io_dataReadBus_resp_data_3_data;
        QData/*63:0*/ __PVT__s3_io_dataWriteBus_req_bits_data_data;
        QData/*63:0*/ __PVT__s3_io_mem_req_bits_wdata;
        QData/*63:0*/ __PVT__s3_io_mem_resp_bits_rdata;
        QData/*63:0*/ __PVT__s3_io_mmio_req_bits_wdata;
        QData/*63:0*/ __PVT__s3_io_mmio_resp_bits_rdata;
        QData/*63:0*/ __PVT__s3_io_cohResp_bits_rdata;
        QData/*63:0*/ __PVT__dataArray_io_r_0_resp_data_0_data;
        QData/*63:0*/ __PVT__dataArray_io_r_0_resp_data_1_data;
        QData/*63:0*/ __PVT__dataArray_io_r_0_resp_data_2_data;
        QData/*63:0*/ __PVT__dataArray_io_r_0_resp_data_3_data;
        QData/*63:0*/ __PVT__dataArray_io_r_1_resp_data_0_data;
        QData/*63:0*/ __PVT__dataArray_io_r_1_resp_data_1_data;
        QData/*63:0*/ __PVT__dataArray_io_r_1_resp_data_2_data;
        QData/*63:0*/ __PVT__dataArray_io_r_1_resp_data_3_data;
        QData/*63:0*/ __PVT__dataArray_io_w_req_bits_data_data;
        QData/*63:0*/ __PVT__arb_io_in_0_bits_wdata;
        QData/*63:0*/ __PVT__arb_io_in_1_bits_wdata;
        QData/*63:0*/ __PVT__arb_io_out_bits_wdata;
        QData/*63:0*/ __PVT__s2_io_in_bits_r_req_wdata;
        QData/*63:0*/ __PVT__s3_io_in_bits_r_req_wdata;
        QData/*63:0*/ __PVT__s3_io_in_bits_r_datas_0_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_r_datas_1_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_r_datas_2_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_r_datas_3_data;
        QData/*63:0*/ __PVT__s3_io_in_bits_r_forwardData_data_data;
        QData/*63:0*/ __Vtogcov__io_in_req_bits_wdata;
        QData/*63:0*/ __Vtogcov__io_in_resp_bits_rdata;
        QData/*63:0*/ __Vtogcov__io_out_mem_req_bits_wdata;
        QData/*63:0*/ __Vtogcov__io_out_mem_resp_bits_rdata;
        QData/*63:0*/ __Vtogcov__io_out_coh_req_bits_wdata;
        QData/*63:0*/ __Vtogcov__io_out_coh_resp_bits_rdata;
        QData/*63:0*/ __Vtogcov__io_mmio_req_bits_wdata;
        QData/*63:0*/ __Vtogcov__io_mmio_resp_bits_rdata;
        QData/*63:0*/ __Vtogcov__s1_io_in_bits_wdata;
        QData/*63:0*/ __Vtogcov__s1_io_out_bits_req_wdata;
        QData/*63:0*/ __Vtogcov__s1_io_dataReadBus_resp_data_0_data;
        QData/*63:0*/ __Vtogcov__s1_io_dataReadBus_resp_data_1_data;
        QData/*63:0*/ __Vtogcov__s1_io_dataReadBus_resp_data_2_data;
        QData/*63:0*/ __Vtogcov__s1_io_dataReadBus_resp_data_3_data;
        QData/*63:0*/ __Vtogcov__s2_io_in_bits_req_wdata;
        QData/*63:0*/ __Vtogcov__s2_io_out_bits_req_wdata;
        QData/*63:0*/ __Vtogcov__s2_io_out_bits_datas_0_data;
        QData/*63:0*/ __Vtogcov__s2_io_out_bits_datas_1_data;
        QData/*63:0*/ __Vtogcov__s2_io_out_bits_datas_2_data;
        QData/*63:0*/ __Vtogcov__s2_io_out_bits_datas_3_data;
        QData/*63:0*/ __Vtogcov__s2_io_out_bits_forwardData_data_data;
        QData/*63:0*/ __Vtogcov__s2_io_dataReadResp_0_data;
        QData/*63:0*/ __Vtogcov__s2_io_dataReadResp_1_data;
        QData/*63:0*/ __Vtogcov__s2_io_dataReadResp_2_data;
        QData/*63:0*/ __Vtogcov__s2_io_dataReadResp_3_data;
    };
    struct {
        QData/*63:0*/ __Vtogcov__s2_io_dataWriteBus_req_bits_data_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_req_wdata;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_datas_0_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_datas_1_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_datas_2_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_datas_3_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_forwardData_data_data;
        QData/*63:0*/ __Vtogcov__s3_io_out_bits_rdata;
        QData/*63:0*/ __Vtogcov__s3_io_dataReadBus_resp_data_0_data;
        QData/*63:0*/ __Vtogcov__s3_io_dataReadBus_resp_data_1_data;
        QData/*63:0*/ __Vtogcov__s3_io_dataReadBus_resp_data_2_data;
        QData/*63:0*/ __Vtogcov__s3_io_dataReadBus_resp_data_3_data;
        QData/*63:0*/ __Vtogcov__s3_io_dataWriteBus_req_bits_data_data;
        QData/*63:0*/ __Vtogcov__s3_io_mem_req_bits_wdata;
        QData/*63:0*/ __Vtogcov__s3_io_mem_resp_bits_rdata;
        QData/*63:0*/ __Vtogcov__s3_io_mmio_req_bits_wdata;
        QData/*63:0*/ __Vtogcov__s3_io_mmio_resp_bits_rdata;
        QData/*63:0*/ __Vtogcov__s3_io_cohResp_bits_rdata;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_0_resp_data_0_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_0_resp_data_1_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_0_resp_data_2_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_0_resp_data_3_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_1_resp_data_0_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_1_resp_data_1_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_1_resp_data_2_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_r_1_resp_data_3_data;
        QData/*63:0*/ __Vtogcov__dataArray_io_w_req_bits_data_data;
        QData/*63:0*/ __Vtogcov__arb_io_in_0_bits_wdata;
        QData/*63:0*/ __Vtogcov__arb_io_in_1_bits_wdata;
        QData/*63:0*/ __Vtogcov__arb_io_out_bits_wdata;
        QData/*63:0*/ __Vtogcov__s2_io_in_bits_r_req_wdata;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_r_req_wdata;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_r_datas_0_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_r_datas_1_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_r_datas_2_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_r_datas_3_data;
        QData/*63:0*/ __Vtogcov__s3_io_in_bits_r_forwardData_data_data;
        QData/*63:0*/ __Vdly__s2_io_in_bits_r_req_wdata;
        QData/*63:0*/ __Vdly__s3_io_in_bits_r_req_wdata;
        QData/*63:0*/ __Vdly__s3_io_in_bits_r_datas_0_data;
        QData/*63:0*/ __Vdly__s3_io_in_bits_r_datas_1_data;
        QData/*63:0*/ __Vdly__s3_io_in_bits_r_datas_2_data;
        QData/*63:0*/ __Vdly__s3_io_in_bits_r_datas_3_data;
        QData/*63:0*/ __Vdly__s3_io_in_bits_r_forwardData_data_data;
    };

    // INTERNAL VARIABLES
    Vnutshellcache__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vnutshellcache_Cache(Vnutshellcache__Syms* symsp, const char* v__name);
    ~Vnutshellcache_Cache();
    VL_UNCOPYABLE(Vnutshellcache_Cache);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __vlCoverInsert(std::atomic<uint32_t>* countp, bool enable, const char* filenamep, int lineno, int column,
        const char* hierp, const char* pagep, const char* commentp, const char* linescovp);
};


#endif  // guard
